### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GioviQ** [cezarypiatek/CsharpMacros#14]
I see your interesting macros work at design time, but e.g. if SampleType in macros.properties(SampleType) changes you have to create macro again.

Do you think is possible to implement something transparent to developer to avoid this?

**Comment by cezarypiatek** [comment]
Hi @GioviQ 
Not sure what you mean by `transparent to developer`.  CsharpMacros works purely on design time. Recreating the same macro over and over again can be very tedious and I've been thinking about creating some sort of stash for reusable macros. If you need something that works on build time then you should try to use T4 templates or you might be interested in my other project which was described in this blog post  https://cezarypiatek.github.io/post/generate-mappings-on-build/

**Comment by GioviQ** [comment]
I think something working like #define in C++.
I know T4, but it does not work inline for only a piece of code in a cs file.
