### ISSUE TITLE
How do I tell a macro where to stop processing

### ISSUE THREAD

**Issue by TheMouster** [cezarypiatek/CsharpMacros#4]
Love the tool. Looks like it will be very handy for me.

One problem I'm encountering is where I construct a macro in the middle of my code and it wants to duplicate everything below it, not just the code in the comment. How do I tell the macro where it's boundary is?

Visual Studio 2019, Windows 7 64bit.

**Comment by TheMouster** [comment]
FYI: No Resharper.

**Comment by TheMouster** [comment]
Also, I'm using the values setting e.g.

// macros.values(A,B,C)
// console.writeline(${value});

**Comment by cezarypiatek** [comment]
Hi,
Everything commented below the macro header  `// macros.values(A,B,C)` is treated as a macro `template` and `template` will be repeated for every element returned by the `macro function`. 
Everything that you want to repeat should be included in this commented template.

**Comment by TheMouster** [comment]
Hi,

It's repeating code outside of the comment as well e.g.

// macros.values(A,B,C)
// Console.WriteLine("${value}");

Console.WriteLine("TheMouster");

results in

Console.WriteLine("A");

Console.WriteLine("TheMouster");

Console.WriteLine("B");

Console.WriteLine("TheMouster");

Console.WriteLine("C");

Console.WriteLine("TheMouster");

Where as I would expect;

Console.WriteLine("A");
Console.WriteLine("B");
Console.WriteLine("C");
Console.WriteLine("TheMouster");

**Comment by cezarypiatek** [comment]
Can you provide a sample project with a code that cause that problem? I'm using VS2019 and I'm not able to reproduce described issue:
![reproduce_failed](https://user-images.githubusercontent.com/7759991/64186106-900ce780-ce6e-11e9-8d2b-f4a579207dc2.gif)


Please make sure that you have installed the newest version from the marketplace.

**Comment by cezarypiatek** [comment]
@TheMouster do you still experience this problem?

**Comment by cezarypiatek** [comment]
Closing because the lack of the response
