### ISSUE TITLE
Feature Request: For loop

### ISSUE THREAD

**Issue by EMostafaAli** [cezarypiatek/CsharpMacros#9]
Thanks for this initiative/project.
It would be wonderful if it includes for loop. For example

```
//macros.For(i = 0, i < 10, i++)
//var v.${i} = new SomeClass(${i});
```

This generates the following:
```
var v1 = new SomeClass(1)
var v2 = new SomeClass(2)
...
```

**Comment by cezarypiatek** [comment]
Hi,

In CSharpMacros convention it should be rather

```
//macros.range(0, 10)
//var v.${item} = new SomeClass(${item});
``` 

I will try to implement it. Thanks for the idea

**Comment by cezarypiatek** [comment]
Feature implemented and release. Please check https://github.com/cezarypiatek/CsharpMacros#range for the details
